name: writer-build

on:
  pull_request:
    paths:
      - "src/Model/**"
      - "src/Writer/**"
      - ".github/workflows/writer-build.yml"
  push:
    paths:
      - "src/Model/**"
      - "src/Writer/**"
      - ".github/workflows/writer-build.yml"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build
      run: dotnet build --configuration Release src/EasyRates.sln
    - name: Test
      run: |
        dotnet test --configuration Release src/Model/EasyRates.Model.Tests/EasyRates.Model.Tests.csproj
        dotnet test --configuration Release src/Writer/EasyRates.Writer.Tests/EasyRates.Writer.Tests.csproj
